
package presentacion.homepagePanel;

import dominio.InfoAdicional;
import dominio.Perfil;
import dominio.Sesion;
import java.awt.BorderLayout;
import java.awt.Color;

import java.awt.Font;
import java.util.List;
import java.util.stream.Collectors;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import presentacion.inicioSesion.InicioSesionFrm;
import servicios.LikeService;
import servicios.PerfilService;

/**
 *
 * @author demib
 */
public class FrmBuscar extends javax.swing.JFrame {
    
    private JButton btnActual;
    
    private PnlPerfilCard pnlPerfilCard;
    
    
    private List<Perfil> perfiles;
    private int indiceActual = 0;
    private PerfilService perfilService = new PerfilService();
    private LikeService likeService = new LikeService();
    


    /**
     * Creates new form FrmBuscar
     */
    public FrmBuscar() {
        
        
        initComponents();
        setLocationRelativeTo(null);

        btnActual = btnBuscar; // btn seleccionado al iniciar
        seleccionarBtn(btnBuscar);
        
        configurarPnlMain();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrarSesionBtn = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnMatches = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(390, 844));

        pnlHeader.setBackground(new java.awt.Color(245, 245, 245));
        pnlHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        pnlHeader.setPreferredSize(new java.awt.Dimension(390, 50));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Explorar");

        cerrarSesionBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cerrarSesionBtn.setText("<html>Cerrar<br>Sesión</html>");
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(cerrarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(cerrarSesionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlMain.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pnlBottom.setBackground(new java.awt.Color(245, 245, 245));
        pnlBottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        pnlBottom.setPreferredSize(new java.awt.Dimension(390, 50));

        btnBuscar.setBackground(new java.awt.Color(245, 245, 245));
        btnBuscar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(204, 204, 204));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setPreferredSize(new java.awt.Dimension(75, 23));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnMatches.setBackground(new java.awt.Color(245, 245, 245));
        btnMatches.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMatches.setForeground(new java.awt.Color(204, 204, 204));
        btnMatches.setText("Matches");
        btnMatches.setBorder(null);
        btnMatches.setBorderPainted(false);
        btnMatches.setContentAreaFilled(false);
        btnMatches.setFocusPainted(false);
        btnMatches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMatchesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMatchesMouseExited(evt);
            }
        });
        btnMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchesActionPerformed(evt);
            }
        });

        btnPerfil.setBackground(new java.awt.Color(245, 245, 245));
        btnPerfil.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(204, 204, 204));
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setFocusPainted(false);
        btnPerfil.setPreferredSize(new java.awt.Dimension(75, 23));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfilMouseExited(evt);
            }
        });
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMatches, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(btnMatches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        // TODO add your handling code here:
        btnBuscar.setForeground(Color.decode("#0078C2"));
        
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
        if(!btnBuscar.equals(btnActual)) // ← solo gris si NO está seleccionado
        btnBuscar.setForeground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        seleccionarBtn(btnBuscar);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMatchesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatchesMouseEntered
        // TODO add your handling code here:
        btnMatches.setForeground(Color.decode("#0078C2"));
    }//GEN-LAST:event_btnMatchesMouseEntered

    private void btnMatchesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatchesMouseExited
        // TODO add your handling code here:
        if(!btnMatches.equals(btnActual)) // ← solo gris si NO está seleccionado
        btnMatches.setForeground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_btnMatchesMouseExited

    private void btnMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchesActionPerformed
        // TODO add your handling code here:
        seleccionarBtn(btnMatches);
    }//GEN-LAST:event_btnMatchesActionPerformed

    private void btnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseEntered
        // TODO add your handling code here:
        btnPerfil.setForeground(Color.decode("#0078C2"));
    }//GEN-LAST:event_btnPerfilMouseEntered

    private void btnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseExited
        // TODO add your handling code here:
        if(!btnPerfil.equals(btnActual)) // ← solo gris si NO está seleccionado
        btnPerfil.setForeground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_btnPerfilMouseExited

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        seleccionarBtn(btnPerfil);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        try {
            JOptionPane.showConfirmDialog(this, 
                    "Esta apunto de cerrar sesion ¿Desea continuar?", 
                    "Cerrando sesion", 
                    WIDTH);
            
            Sesion.cerrarSesion();
            
            InicioSesionFrm inicioSesion = new InicioSesionFrm();
            inicioSesion.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error del Sistema",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMatches;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
    
    
    private void seleccionarBtn(JButton btnActivo) {
        // Primero todos a gris
        btnBuscar.setForeground(Color.decode("#CCCCCC"));
        btnMatches.setForeground(Color.decode("#CCCCCC"));
        btnPerfil.setForeground(Color.decode("#CCCCCC"));

        // Solo el clickeado a azul
        btnActivo.setForeground(Color.decode("#0078C2"));
        
        //Guarda cual esta activo
        btnActual = btnActivo;
    }
    
    private void configurarPnlMain() {
        pnlMain.setLayout(new BorderLayout());
    
        // 1. Cargar todos los perfiles de la BD (excepto el tuyo)
        perfiles = perfilService.listar(); 
    
        // 2. Mostrar el primero
        mostrarPerfilActual();
    }
    
    private void mostrarPerfilActual() {
        pnlMain.removeAll(); // Limpia el panel antes de mostrar el siguiente

        if (perfiles == null || perfiles.isEmpty() || indiceActual >= perfiles.size()) {
            // No hay mas perfiles
            JLabel lbl = new JLabel("No hay más perfiles por ver", SwingConstants.CENTER);
            lbl.setFont(new Font("Arial", Font.BOLD, 18));
            pnlMain.add(lbl, BorderLayout.CENTER);
            pnlMain.revalidate();
            pnlMain.repaint();
            return;
        }

        // Obtener el perfil actual
        Perfil perfil = perfiles.get(indiceActual);

        // Armar los intereses como String desde el Set<InfoAdicional>
        String intereses = perfil.getPerfilInfoAdicional() != null
            ? perfil.getPerfilInfoAdicional().stream()
                  .map(InfoAdicional::getNombre) 
                  .collect(Collectors.joining(", "))
            : "Sin intereses";

        // Crear el card con datos reales
        pnlPerfilCard = new PnlPerfilCard(
            perfil.getNombre(),
            perfil.getCarrera().toString(), 
            intereses,
            perfil.getFotoPerfil() 
        );

        
        //  Boton Me Gusta
        pnlPerfilCard.getBtnMeGusta().addActionListener(e -> {
            
            Perfil perfilOrigen = Sesion.getPerfilActivo();
            
            
            boolean hayMatch = likeService.enviarLike(perfilOrigen, perfil, true); // Si le gusto
            
            if(hayMatch){
                JOptionPane.showMessageDialog(this,
                "¡Es un match con " + perfil.getNombre() + "!",
                "¡Match!",
                JOptionPane.INFORMATION_MESSAGE);
            }
            
            System.out.println("Le gusto: " + perfil.getNombre());
            
            
            
            indiceActual++;
            mostrarPerfilActual();
        });
        

        // Boton No me interesa
        pnlPerfilCard.getBtnNoMeInteresa().addActionListener(e -> {
            Perfil perfilOrigen = Sesion.getPerfilActivo();
            
            
            likeService.enviarLike(perfilOrigen, perfil, false); // No le gusto
            
            System.out.println("No le intereso: " + perfil.getNombre());
            
            indiceActual++;
            mostrarPerfilActual();
        });

        pnlMain.add(pnlPerfilCard, BorderLayout.CENTER);
        pnlMain.revalidate();
        pnlMain.repaint();
    }
}
