/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.inicioSesion;

//import SiguientePantallaPrueba.SiguientePantallaPruebaFrm;
import presentacion.registroPanel.RegistroUsuarioFrm;
import jakarta.persistence.EntityManager;
import presentacion.bienvenida.BienvenidaFrm;

/**
 *
 * @author 52644
 */
public class InicioSesionFrm extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesionFrm
     */
    public InicioSesionFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPnl = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        inicioSesionHeaderLbl = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        camposPnl = new javax.swing.JPanel();
        iniciarSesionBtn = new javax.swing.JButton();
        contrasenaTxt = new javax.swing.JTextField();
        correoTxt = new javax.swing.JTextField();
        correoLbl = new javax.swing.JLabel();
        ContrasenaLbl = new javax.swing.JLabel();
        registrarseBtn = new javax.swing.JButton();
        inisioSesionLbl = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 120, 194));
        setMinimumSize(new java.awt.Dimension(390, 844));
        setSize(new java.awt.Dimension(390, 844));

        fondoPnl.setBackground(new java.awt.Color(0, 120, 194));
        fondoPnl.setForeground(new java.awt.Color(0, 120, 194));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setMaximumSize(null);

        inicioSesionHeaderLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inicioSesionHeaderLbl.setForeground(new java.awt.Color(0, 0, 0));
        inicioSesionHeaderLbl.setText("Inicio de Sesión");

        regresarBtn.setBackground(new java.awt.Color(255, 255, 255));
        regresarBtn.setForeground(new java.awt.Color(0, 0, 0));
        regresarBtn.setText("<-");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regresarBtn)
                .addGap(65, 65, 65)
                .addComponent(inicioSesionHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(inicioSesionHeaderLbl)
                .addComponent(regresarBtn))
        );

        camposPnl.setBackground(new java.awt.Color(255, 255, 255));
        camposPnl.setMinimumSize(new java.awt.Dimension(324, 602));
        camposPnl.setPreferredSize(new java.awt.Dimension(324, 602));

        iniciarSesionBtn.setBackground(new java.awt.Color(0, 0, 0));
        iniciarSesionBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        iniciarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesionBtn.setText("INICIAR SESIÓN");
        iniciarSesionBtn.setPreferredSize(new java.awt.Dimension(111, 26));
        iniciarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBtnActionPerformed(evt);
            }
        });

        contrasenaTxt.setBackground(new java.awt.Color(249, 249, 249));

        correoTxt.setBackground(new java.awt.Color(249, 249, 249));

        correoLbl.setBackground(new java.awt.Color(0, 0, 0));
        correoLbl.setForeground(new java.awt.Color(0, 0, 0));
        correoLbl.setText("Correo:");

        ContrasenaLbl.setForeground(new java.awt.Color(0, 0, 0));
        ContrasenaLbl.setText("Contraseña:");

        registrarseBtn.setBackground(new java.awt.Color(255, 255, 255));
        registrarseBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        registrarseBtn.setForeground(new java.awt.Color(0, 51, 255));
        registrarseBtn.setText("<html><u>¿Aún no tienes cuenta? Regístrate</u></html>");
        registrarseBtn.setToolTipText("");
        registrarseBtn.setBorder(null);
        registrarseBtn.setBorderPainted(false);
        registrarseBtn.setContentAreaFilled(false);
        registrarseBtn.setFocusPainted(false);
        registrarseBtn.setFocusable(false);
        registrarseBtn.setRolloverEnabled(false);
        registrarseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseBtnActionPerformed(evt);
            }
        });

        inisioSesionLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inisioSesionLbl.setForeground(new java.awt.Color(0, 0, 0));
        inisioSesionLbl.setText("Inicio de Sesión");

        javax.swing.GroupLayout camposPnlLayout = new javax.swing.GroupLayout(camposPnl);
        camposPnl.setLayout(camposPnlLayout);
        camposPnlLayout.setHorizontalGroup(
            camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camposPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inisioSesionLbl)
                    .addGroup(camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ContrasenaLbl)
                        .addComponent(correoLbl)
                        .addComponent(iniciarSesionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contrasenaTxt)
                        .addComponent(correoTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registrarseBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        camposPnlLayout.setVerticalGroup(
            camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camposPnlLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(inisioSesionLbl)
                .addGap(38, 38, 38)
                .addComponent(correoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(ContrasenaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(iniciarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(registrarseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout fondoPnlLayout = new javax.swing.GroupLayout(fondoPnl);
        fondoPnl.setLayout(fondoPnlLayout);
        fondoPnlLayout.setHorizontalGroup(
            fondoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPnlLayout.createSequentialGroup()
                .addGroup(fondoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(fondoPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(camposPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoPnlLayout.setVerticalGroup(
            fondoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoPnlLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(camposPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        getContentPane().add(fondoPnl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBtnActionPerformed
 limpiarBordes();

    if (!validarCamposLogin()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor completa todos los campos correctamente",
                "Error de Validación",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String correo = correoTxt.getText().trim();
    String contrasena = contrasenaTxt.getText().trim();
    
    // Configuración para ambiente local
    String direccionIp = "127.0.0.1";
    String tipoDispositivo = "DESKTOP";

    try {
        servicios.PerfilService perfilService = new servicios.PerfilService();
        
        // Autenticar y crear sesión
        dominio.SesionActiva sesion = perfilService.autenticarYCrearSesion(
            correo, 
            contrasena, 
            tipoDispositivo, 
            direccionIp
        );

        if (sesion != null) {
            // Sesión creada exitosamente
            dominio.Perfil perfilAutenticado = sesion.getPerfil();
            
            // Guardar sesión en el contexto global
            presentacion.sesion.SesionGlobal.iniciarSesion(sesion);
            
            javax.swing.JOptionPane.showMessageDialog(this,
                    "¡Bienvenido " + perfilAutenticado.getNombre() + "!",
                    "Autenticación Exitosa",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
/* Abrir siguiente pantalla
            
            SiguientePantallaPruebaFrm siguiente = new SiguientePantallaPruebaFrm();
            siguiente.setVisible(true);


            this.dispose(); 
            
    //Cerrar login
 */           
        } else {
            // Autenticación fallida - identificar el error
            EntityManager em = utils.JPAUtil.getEntityManager();
            try {
                dominio.Perfil perfilExistente = new persistencia.PerfilDAO()
                    .buscarPorCorreo(correo, em);

                if (perfilExistente == null) {
                    correoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(
                        java.awt.Color.RED, 2));
                    correoTxt.setText("");
                    contrasenaTxt.setText("");
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "El correo ingresado no existe",
                            "Error de Autenticación",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    correoTxt.requestFocus();
                } else {
                    contrasenaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(
                        java.awt.Color.RED, 2));
                    contrasenaTxt.setText("");
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "La contraseña es incorrecta",
                            "Error de Autenticación",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    contrasenaTxt.requestFocus();
                }
            } finally {
                em.close();
            }
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Error del Sistema: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_iniciarSesionBtnActionPerformed

    private void registrarseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseBtnActionPerformed

    RegistroUsuarioFrm registroFrame = new RegistroUsuarioFrm();
    registroFrame.setVisible(true);
    

    this.dispose();
    }//GEN-LAST:event_registrarseBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:

        
    BienvenidaFrm bienvenidaFrame = new BienvenidaFrm();
    bienvenidaFrame.setVisible(true);
    

    this.dispose();

    }//GEN-LAST:event_regresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContrasenaLbl;
    private javax.swing.JPanel camposPnl;
    private javax.swing.JTextField contrasenaTxt;
    private javax.swing.JLabel correoLbl;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JPanel fondoPnl;
    private javax.swing.JButton iniciarSesionBtn;
    private javax.swing.JLabel inicioSesionHeaderLbl;
    private javax.swing.JLabel inisioSesionLbl;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JButton registrarseBtn;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables

private boolean validarCamposLogin() {
  boolean esValido = true;
    String mensaje = "";
    
    String correo = correoTxt.getText().trim();
    String contrasena = contrasenaTxt.getText().trim();
    
    if (correo.isEmpty()) {
        correoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
        mensaje += "El correo es obligatorio.\n";
        esValido = false;
    } else if (!esCorreoValido(correo)) {
        correoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
        mensaje += "El correo debe ser institucional (@potros.itson.edu.mx).\n";
        esValido = false;
    } else {
        correoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1));
    }
    
    if (contrasena.isEmpty()) {
        contrasenaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
        mensaje += "La contraseña es obligatoria.";
        esValido = false;
    } else {
        contrasenaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1));
    }
    
    if (!esValido) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            mensaje, 
            "Error de Validación", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
    return esValido;
}

private boolean esCorreoValido(String correo) {
    String patronCorreo = "^[a-zA-Z0-9._%+-]+@potros\\.itson\\.edu\\.mx$";
    return correo.matches(patronCorreo);
}

private void limpiarBordes() {
    correoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1));
    contrasenaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1));
}

}
